# 
# Solution to Project Euler problem 2
# Copyright (c) Süleyman Onur Dinçel. All rights reserved.
# 
# https://github.com/onurdincel/Project-Euler-Solutions
# 

"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

def calculate():
    
    answer = 0
    x = 1
    y = 2 

    while (True):
        if x <= 4000000:
            if x % 2 == 0:
                answer += x
            x , y = y , x + y
        else:
            break
    return str(answer)

if __name__ == "__main__":
	print(calculate())